# Generated by Django 4.0.5 on 2022-06-11 19:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_day', models.DateField()),
                ('in_date', models.DateTimeField(null=True)),
                ('out_date', models.DateTimeField(null=True)),
                ('work_time', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)])),
                ('break_time', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)])),
            ],
            options={
                'verbose_name_plural': '일별출입기록',
                'db_table': 'gate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField()),
                ('tag', models.CharField(choices=[('IN', '출근'), ('OUT', '퇴근')], max_length=6, null=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inout', to='gate.gate')),
            ],
            options={
                'verbose_name_plural': '출입기록',
            },
        ),
    ]
