# Generated by Django 4.0.5 on 2022-06-11 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
